on:
  pull_request:
  push:
    branches:
      - main

name: CI

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.11"
          - "3.14"
        runs-on:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        include:
          - python-version: 3.15.0rc3
            runs-on: ubuntu-latest
        exclude:
          - python-version: "3.11"
            runs-on: windows-latest
    name: Tests ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v7
      
      - uses: astral-sh/setup-uv@v10.2.0

      - run: uv run --python=${{ matrix.python-version }} pytest
